### ISSUE TITLE
Make SeeCompatTable macro do nothing

### ISSUE THREAD

**Issue by a2sheppy** [mdn/kumascript#1360]
Since we don't want the SeeCompatTable banner at the tops of pages anymore, and we will be importing all this content into another platform at some point anyway, let's make that macro a no-op so we don't have to actually go and remove that from everyplace currently using it.

**Comment by peterbe** [comment]
> Since we don't want the SeeCompatTable banner at the tops of pages anymore

**Is that a solid made decision somewhere?**
If so, I'd be happy to tackle this one. 

I noticed that it's used in 3,412 (1,387 en-US) pages. So turning the macro into one that does a void would be a good idea. 
But I wonder, should we perhaps change the macro to not just be an empty string returned, but perhaps a HTML comment, like `<!-- the SeeCompatTable macro is deprecated. You can delete any mentions of '{{SeeCompatTable}}' -->`

By the way, getting rid of them would be nice since it'd resolve the double-icon bug which still seems to be present:
<img width="691" alt="Screen Shot 2020-04-22 at 11 40 29 AM" src="https://user-images.githubusercontent.com/26739/80002803-1f165080-848e-11ea-8be3-0baebb6149a7.png">

**Comment by a2sheppy** [comment]
This decision (to stop using SeeCompatTable) was made, gosh, a couple years ago maybe. It's just been slow to get rid of, and some folks haven't picked up on that change and have continued using it.

**Comment by peterbe** [comment]
In that case, I'd be happy to work on this. 
And I think I'd like to opt-out from replacing the macro with a HTML comment and just make it an empty string instead.

**Comment by a2sheppy** [comment]
I agree.


Eric "Sheppy" Shepherd
Senior Technical Writer
MDN Web Docs
Mozilla

**Comment by ExE-Boss** [comment]
That double icon bug is because some old pages still haven’t been re‑rendered.

I fixed that in <https://github.com/mdn/kumascript/pull/1264> (<https://github.com/mdn/kumascript/commit/3a3d25c428d047569f53ece3f0bea030852469eb>)
