### ISSUE TITLE
Compat Macro Bug

### ISSUE THREAD

**Issue by jpmedley** [mdn/kumascript#1444]
The Compat() macro is putting this error on [CSSTransformComponent.toString()](https://wiki.developer.mozilla.org/en-US/docs/Web/API/CSSTransformComponent/toString). I can't finds an error either on the page's use of the macro or in the JSON file that it's loading.

![image](https://user-images.githubusercontent.com/8204171/101217372-172ea980-3636-11eb-933c-6a348a375a36.png)

**Comment by peterbe** [comment]
At least https://developer.allizom.org/en-US/docs/Web/API/CSSTransformComponent/toString isn't crashing anymore. On Stage. But, as mentioned in some other issue, unfortunately, it doesn't display there that was *supposed* to be a BCD table there. That's what https://github.com/mdn/yari/issues/2066 is for.

PS. the reason it was crashing the page was because the query resolved to look for an API method named (exactly) `toString` with is one of those built-ins in JavaScript. 
```
> thing = {}
{}
> if (thing['toString']) { console.log("Heck yea!") }
Heck yea!
```

**Comment by jpmedley** [comment]
That's the first thing I checked and there is such a key in the data. That's why I opened the ticket.
