### ISSUE TITLE
Several spec URLs are outdated

### ISSUE THREAD

**Issue by TimothyGu** [mdn/kumascript#442]
Pretty much all the obsoleted W3C DOM spec links in https://github.com/mdn/kumascript/blob/master/macros/SpecName.ejs now 404 when requested.

Example: https://developer.mozilla.org/en-US/docs/Web/API/NodeFilter#Specification links to https://www.w3.org/TR/DOM-Level-2-Traversal-Range/traversal.html#Traversal-NodeFilter through `{{SpecName('DOM2 Traversal_Range', 'traversal.html#Traversal-NodeFilter', 'NodeFilter')}}`, which is now known as https://www.w3.org/TR/2000/REC-DOM-Level-2-Traversal-Range-20001113/traversal.html#Traversal-NodeFilter.

**Comment by tshinnic** [comment]
Another example and possible explanation, with a "how do you fix that?" question.

Article [UIEvent](https://developer.mozilla.org/en-US/docs/Web/API/UIEvent) references spec "DOM Level 2 Events" using "https://www.w3.org/TR/DOM-Level-2-Events/events.html#Events-UIEvent" which is 
- "https://www.w3.org/TR/DOM-Level-2-Events/" 
plus desired subsection path
- "events.html#Events-UIEvent"

Unfortunately w3.org is trying to redirect logical path 
- "/TR/DOM-Level-2-Events/"
to
- "/TR/2000/REC-DOM-Level-2-Events-20001113/" 

but without fully rewriting the path.

So rather than getting a fully rewritten redirect to 
- "https://www.w3.org/TR/2000/REC-DOM-Level-2-Events-20001113/events.html#Events-UIEvent" 
we get
- "https://www.w3.org/TR/DOM-Level-2-Events/events.html#Events-UIEvent"

which fails with 404 as mentioned above.

Source in the article  [UIEvent](https://developer.mozilla.org/en-US/docs/Web/API/UIEvent) references:
```text
{{SpecName('DOM2 Events', '#Events-UIEvent', 'UIEvent')}}
```
and SpecName.ejs has [embedded data](https://github.com/mdn/kumascript/blob/master/macros/SpecName.ejs#L488-L491)
```javascript
    'DOM2 Events':{
        name : 'Document Object Model (DOM) Level 2 Events Specification',
        url  : 'https://www.w3.org/TR/DOM-Level-2-Events/events.html'
    },
```

w3.org currently rewrites incompletely - even "https://www.w3.org/TR/DOM-Level-2-Events/events.html" will get a 404 - and that is a 'bad' thing.  But it seems icky that we have to drop the logical path in favor of the current physical path.  Do you see any other choice but patching to
```javascript
        url  : 'https://www.w3.org/TR/2000/REC-DOM-Level-2-Events-20001113/events.html'
```

**Comment by tshinnic** [comment]
(Please pardon the wall of text below, but I think I've got all the information you need to decide what to do, and which entries to do it to)

I keep encountering this.  Latest is
* article [getComputedStyle()](https://developer.mozilla.org/en-US/docs/Web/API/Window/getComputedStyle)
* refs [DOM Level 2 Style: getComputedStyle](https://www.w3.org/TR/DOM-Level-2-Style/css.html#CSS-CSSview-getComputedStyle)  
* `/TR/DOM-Level-2-Style/css.html#CSS-CSSview-getComputedStyle`
* but s.b.  [ViewCss - IDL - getComputedStyle](https://www.w3.org/TR/2000/REC-DOM-Level-2-Style-20001113/css.html#CSS-CSSview-getComputedStyle) 
* `/TR/2000/REC-DOM-Level-2-Style-20001113/css.html#CSS-CSSview-getComputedStyle`

**Oh, wait**, that article does not use the SpecName() macro, **but an *external link***. 

Ahhh, but this then **better illustrates the problem, that `w3.org` is not rewriting redirect paths correctly**.
* Fails 404:  https://www.w3.org/TR/DOM-Level-2-Style/css.html#CSS-CSSview-getComputedStyle
* Works: &nbsp; &nbsp; https://www.w3.org/TR/DOM-Level-2-Style/
* Works: &nbsp; &nbsp; https://www.w3.org/TR/2000/REC-DOM-Level-2-Style-20001113/
* Works: &nbsp; &nbsp; https://www.w3.org/TR/2000/REC-DOM-Level-2-Style-20001113/css.html#CSS-CSSview-getComputedStyle

This is the situation with my previous report above, where:
* Fails 404:  https://www.w3.org/TR/DOM-Level-2-Events/events.html
* Works: &nbsp; &nbsp; https://www.w3.org/TR/DOM-Level-2-Events
* Works: &nbsp; &nbsp; https://www.w3.org/TR/2000/REC-DOM-Level-2-Events-20001113/events.html

And the first report using `{{SpecName('DOM2 Traversal_Range', 'traversal.html#Traversal-NodeFilter', 'NodeFilter')}}` would have tried:
* Fails 404: https://www.w3.org/TR/DOM-Level-2-Traversal-Range/traversal.html#Traversal-NodeFilter
* Works: &nbsp; &nbsp; https://www.w3.org/TR/DOM-Level-2-Traversal-Range/
* Works: &nbsp; &nbsp; https://www.w3.org/TR/2000/REC-DOM-Level-2-Traversal-Range-20001113/
* Works: &nbsp; &nbsp; https://www.w3.org/TR/2000/REC-DOM-Level-2-Traversal-Range-20001113/traversal.html#Traversal-NodeFilter


So any reference here within entries using a path/fragment will fail if a `w3.org` redirect is required, e.g. 
```
        url  : 'https://www.w3.org/TR/DOM-Level-2-Events/events.html'
```
But even when the entry has no path/fragment, e.g. 
```
        url  : 'https://www.w3.org/TR/DOM-Level-2-Traversal-Range/'
```
if that is referenced by a SpecName() call using a path/fragment, e.g. 
```
{{SpecName('DOM2 Traversal_Range', 'traversal.html#Traversal-NodeFilter', 'NodeFilter')}}
```
that will fail with "404 Not Found"

Since `w3.org` redirects are broken, every www.w3.org path that results in a redirect, must be specified here with the (current) resolved path.

.

**FYI**: I checked the `wget` responses from all the URLs (294), and categorized all those that received "301 Moved Permanently".   (The one "404 Not Found" is covered in #545)


=== HTTP request sent, awaiting response... **301 Moved Permanently**

**Cosmetic fix** - fix in entries by adding final '/' to path

--2018-01-07 21:17:06--  https://w3c.github.io/webappsec-credential-management
--2018-01-07 21:17:06--  https://w3c.github.io/webappsec-credential-management/

--2018-01-07 21:20:11--  https://wicg.github.io/media-capabilities
--2018-01-07 21:20:12--  https://wicg.github.io/media-capabilities/

--2018-01-07 21:20:15--  https://wicg.github.io/mst-content-hint
--2018-01-07 21:20:15--  https://wicg.github.io/mst-content-hint/

--2018-01-07 21:20:21--  https://w3c.github.io/paint-timing
--2018-01-07 21:20:21--  https://w3c.github.io/paint-timing/


**Not a problem** because redirects are rewritten completely by these sites

--2018-01-07 21:18:13--  https://drafts.csswg.org/css-containment/
--2018-01-07 21:18:13--  https://drafts.csswg.org/css-contain/

--2018-01-07 21:18:22--  https://drafts.csswg.org/css-logical-props/
--2018-01-07 21:18:23--  https://drafts.csswg.org/css-logical/

--2018-01-07 21:20:19--  https://www.khronos.org/opengles/sdk/docs/man/xhtml/
--2018-01-07 21:20:20--  https://www.khronos.org/registry/OpenGL-Refpages/es2.0/xhtml/

--2018-01-07 21:20:20--  https://www.khronos.org/opengles/sdk/docs/man3/html/
--2018-01-07 21:20:20--  https://www.khronos.org/registry/OpenGL-Refpages/es3.0/html/

--2018-01-07 21:20:51--  https://www.khronos.org/registry/typedarray/specs/latest/
--2018-01-07 21:20:51--  http://www.ecma-international.org/ecma-262/6.0/

--2018-01-07 21:21:09--  https://dev.w3.org/2009/dap/vibration/
--2018-01-07 21:21:10--  https://w3c.github.io/vibration/

--2018-01-07 21:21:36--  https://dvcs.w3.org/hg/speech-api/raw-file/tip/webspeechapi.html
--2018-01-07 21:21:36--  https://w3c.github.io/speech-api/webspeechapi.html

--2018-01-07 21:21:40--  https://www.w3.org/TR/WOFF/
--2018-01-07 21:21:41--  https://www.w3.org/TR/2012/REC-WOFF-20121213/
>      (This one is a head-scratcher - can't see why this works, others below don't)



**Real problem** - need to update path in entries  (All tested with actual paths/fragment from the docs to see failures)

--2018-01-07 21:18:44--  https://www.w3.org/TR/DOM-Level-2-Core/
--2018-01-07 21:18:44--  https://www.w3.org/TR/2000/REC-DOM-Level-2-Core-20001113/

--2018-01-07 23:47:42--  https://www.w3.org/TR/DOM-Level-2-Events/
--2018-01-07 23:47:43--  https://www.w3.org/TR/2000/REC-DOM-Level-2-Events-20001113/

--2018-01-07 21:18:45--  https://www.w3.org/TR/DOM-Level-2-HTML/
--2018-01-07 21:18:45--  https://www.w3.org/TR/2003/REC-DOM-Level-2-HTML-20030109/

--2018-01-07 21:18:45--  https://www.w3.org/TR/DOM-Level-2-Style/
--2018-01-07 21:18:46--  https://www.w3.org/TR/2000/REC-DOM-Level-2-Style-20001113/

--2018-01-07 21:18:46--  https://www.w3.org/TR/DOM-Level-2-Traversal-Range/
--2018-01-07 21:18:46--  https://www.w3.org/TR/2000/REC-DOM-Level-2-Traversal-Range-20001113/

--2018-01-07 21:18:46--  https://www.w3.org/TR/DOM-Level-3-Core/
--2018-01-07 21:18:47--  https://www.w3.org/TR/2004/REC-DOM-Level-3-Core-20040407/

--2018-01-07 21:18:48--  https://www.w3.org/TR/DOM-Level-3-XPath/
--2018-01-07 21:18:49--  https://www.w3.org/TR/2004/NOTE-DOM-Level-3-XPath-20040226/



=== HTTP request sent, awaiting response... 301 Moved Permanently
**The certificate's owner does not match hostname ...**


--2018-01-07 21:16:54--  https://www.w3.org/2012/sysapps/web-alarms/
--2018-01-07 21:16:55--  https://web-alarms.sysapps.org/
>    The certificate's owner does not match hostname 'web-alarms.sysapps.org'

--2018-01-07 21:17:04--  https://www.w3.org/2012/sysapps/contacts-manager-api/
--2018-01-07 21:17:04--  https://contacts-manager-api.sysapps.org/
>    The certificate's owner does not match hostname 'contacts-manager-api.sysapps.org'

--2018-01-07 21:20:16--  https://www.w3.org/2012/sysapps/messaging/
--2018-01-07 21:20:16--  https://messaging.sysapps.org/
>    The certificate's owner does not match hostname 'messaging.sysapps.org'

.

So the "good news" is it is only www.w3.org failing to redirect correctly, and then only for 7 references inside SpecName.ejs   Fixing those 7, plus the 4 cosmetic fixes, will 'cure' this glitch with `w3.org`.

**Comment by dontcallmedom** [comment]
I'm looking into the DOM-Level-2 situation on the w3c side.

**Comment by dontcallmedom** [comment]
All the DOM specs redirects have now been fixed - are there other w3.org links identified in this issue that I could help fix?

**Comment by TimothyGu** [comment]
Hooray! Thanks @dontcallmedom.

Not on my end, so I'll close this ticket. But if @tshinnic finds any more problems I'll reopen this.
