### ISSUE TITLE
SeeCompatTable badge link doesn't match CompatibilityTable anchor

### ISSUE THREAD

**Issue by sergeychernyshev** [mdn/kumascript#655]
I was looking at the https://developer.mozilla.org/en-US/docs/Web/API/PerformancePaintTiming page and noticed that a link in the compatibility badge at the top of the page uses a wrong anchor name for linking to compatibility table.

I looked into the code and saw that badge uses a [{{SeeCompatTable}}](https://github.com/mdn/kumascript/blob/master/macros/SeeCompatTable.ejs) template which contains anchor link
```html
...Check the <a href='#Browser_compatibility'>Browser compatibility table</a>...
```
notice `Browser_compatibility` as the name of the target anchor with lower case "c".

At the same time and table itself uses [{{CompatibilityTable}}](https://github.com/mdn/kumascript/blob/master/macros/CompatibilityTable.ejs) template which has `div` "AutoCompatibilityTable" id/name on it:
```html
<a id="AutoCompatibilityTable" name="AutoCompatibilityTable"></a>
```
It looks like it is clearly intended for linking to it.

At the same time page also contains section header called "Browser Compatibility" which automatically converts to `Browser_Compatibility` anchor as well:
```html
<h2 id="Browser_Compatibility">Browser Compatibility</h2>
```
notice a capital "C" in it.

I can only assume that name of the section header is an old convention that was used, but broke because of the "c"/"C" mismatch.

It's my first time trying to edit the article on MDN and I didn't want to edit header in the article without knowing what the plans are for compatibility tables (noticed that new version using data is currently in Beta). Also both of these templates seem to be widely used and I don't know what can go wrong if I start mangling the templates.

**Comment by jwhitlock** [comment]
The link is supposed to be to the "Browser Compatibility" header.  The issue is the section, which should be:

```
<h2 id="Browser_compatibility">Browser compatibility</h2>
```

Our [style guide](https://developer.mozilla.org/en-US/docs/MDN/Contribute/Guidelines/Writing_style_guide#Title_and_heading_capitalization) says to use ``Sentence style capitalization`` for headers, not ``Headline Style Capitalization``.

I've updated https://developer.mozilla.org/en-US/docs/Web/API/PerformancePaintTiming to fix the style. Please do the same if you find other bad headings.

**Comment by sergeychernyshev** [comment]
Will do, thank you.
