### ISSUE TITLE
APIListAlpha macro broken

### ISSUE THREAD

**Issue by christophfriedrich** [mdn/kumascript#933]
The macro is used on this page: https://developer.mozilla.org/en-US/docs/Web/API

It throws an error:
>  There was a scripting error on this page. While it is being addressed by site editors, you can view partial content below.

````
Problem executing template APIListAlpha:
    1 | <p>...</p>
    2 | 
    3 | <div>{{APIListAlpha}}</div>
-------------^

SyntaxError: ejs:1
 >> 1| <%
    2| // Creates a list of API Interfaces sorted alphabeticlly
    3| 
    4| var APIHref = $0 || '/en-US/docs/Web/API';

Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.fetchJSONResource (eval at compile (/node_modules/ejs/lib/ejs.js:549:12), <anonymous>:292:21)
    at cls.subpagesExpand (eval at compile (/node_modules/ejs/lib/ejs.js:549:12), <anonymous>:89:28)
    at eval (eval at compile (/node_modules/ejs/lib/ejs.js:549:12), <anonymous>:76:18)
    at returnedFn (/node_modules/ejs/lib/ejs.js:580:17)
    at /app/lib/kumascript/templates.js:71:26
````

Seems like the script is treated as JSON?! I have extremely little knowledge of MDN, so I can't fix it myself, but at least I wanted to let you know.

**Comment by jwhitlock** [comment]
These tracebacks are nearly impossible to read. The last call (``JSON.parse``) is listed first, so it is better to read bottom to top. 

The first two calls (``templates.js`` and ``returnedFn``) are part of the rendering boilerplate, and can be ignored. The first useful call is the third from the bottom.  ``at eval (eval at compile (/node_modules/ejs/lib/ejs.js:549:12), <anonymous>:76:18)`` looks to be this line in ``APIListAlpha``:

https://github.com/mdn/kumascript/blob/26875c588c9fc9a6c3a2aa5be5abd813557beb1f/macros/APIListAlpha.ejs#L68

I'm not sure how line 68 becomes ``<anonymous>:76:18``, JavaScript and EJS is strange.  ``subpagesExpand`` is in ``DekiScript-Page``:

https://github.com/mdn/kumascript/blob/b7f97c51dd2d8dea4bdd0e9be9eb12327165fa67/macros/DekiScript-Page.ejs#L70-L91

This sets up a call to ``fetchJSONResource`` with the URL of http://developer.mozilla.org/en-US/docs/Web/API$children?expand:

https://github.com/mdn/kumascript/blob/26875c588c9fc9a6c3a2aa5be5abd813557beb1f/macros/MDN-Common.ejs#L275-L284

This requests a very big JSON blob, and then parses it. The unexpected response was probably a server error, starting with ``<html>``, rather than the expected start of a JSON payload. This was also probably a temporary error.

I force-refreshed the page, and the error went away. Thank you for the report.
